name: CodeCov
on: push
env:
  PYTHON: '3.9'
steps:
  - name: 'generate report'
    run: python -m unittest
  - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage
        flags: unittests
        fail_ci_if_error: true